### ISSUE TITLE
赞助

### ISSUE THREAD

**Issue by usagiryu** [easychen/not-only-fans#3]
大佬好，这个项目有实际的运营计划么？是否接受赞助呢？有没有有效的渠道可以建立联系，期待和大佬聊聊。可以发邮件给我 tu@rss3.io

**Comment by easychen** [comment]
感谢支持，项目的前身曾在一个稳定币环境尝试运营，但因为攒不齐种子用户没能继续 😂  这个项目长期来讲我是乐观的，短期来讲我是悲观的（因为需求的不确定性和进入门槛），所以在确定后期开发规划之前就先不接受赞助了。我会邮件你我的Telegram。

**Comment by p1slave** [comment]
想问下这个网站现在还运营吗？网站链接打不开了。。话说回来onlyfans类似的平台在国内估计是违法，而且国内的大多数人没有收费订阅的习惯，还是要放到国外市场才能有用户。

**Comment by easychen** [comment]
> 想问下这个网站现在还运营吗？网站链接打不开了。。话说回来onlyfans类似的平台在国内估计是违法，而且国内的大多数人没有收费订阅的习惯，还是要放到国外市场才能有用户。

① 我们并不打算运营，尤其是在大陆不允许加密货币业务以后。② NOF 是通用型数字内容订阅平台，不（只）是用来放某些内容的。这主要由架设者和当地法律决定。

**Comment by p1slave** [comment]
考虑以后在国外传承你的衣钵哈哈，国外数字币可以流通的。可以加个联系方式吗比如telegram如果方便的话，我的邮箱是p1slave@protonmail.com。

**Comment by easychen** [comment]
> 考虑以后在国外传承你的衣钵哈哈，国外数字币可以流通的。可以加个联系方式吗比如telegram如果方便的话，我的邮箱是[p1slave@protonmail.com](mailto:p1slave@protonmail.com)。

https://t.me/easyusetg
