### ISSUE TITLE
Issues running Docker image

### ISSUE THREAD

**Issue by ghost** [easychen/not-only-fans#4]
Hi, I try to run this project with docker following your README. But there are two issues that i don't know how manage:

After login to the client i get this message: `Please install MetaMask or something like plug-ins first`. How I can install this plugin?

The second is that when I try to create a new column nothing append. So I check the js console and i get this error: ` Cannot read properties of undefined (reading 'utils')`.

Can you help me?

Thanks a lot.

**Comment by easychen** [comment]
You need ETH to create a column, so install MetaMask( https://metamask.io/ ) first

**Comment by ghost** [comment]
Thanks!
